- CHANGELOG.md
- src/BucketInfo.ts
- src/BucketSettings.ts
- src/EntryInfo.ts
- src/ServerInfo.ts
The client code should be easier. When we use `BigInt` we should call `valueOf()` to get the primitive.
> Use bigint instead of BigInt

- CHANGELOG.md
- README.md
- src/Client.ts
- src/ServerInfo.ts
- test/Client.test.ts
> [#19] Update to HTTP API v0.5

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/Bucket.ts
- src/Record.ts
- test/Bucket.test.ts
- test/Client.test.ts
Closes #36 
Feature 
We supported v0.6
We support the API v0.7 with querying data, which is implemented as `Bucket.query` method
It doesn't,  but `Bucket.list` is deprecated now.
> [#36] Support Reduct Storage API v0.7

- CHANGELOG.md
- package-lock.json
- package.json
- src/Client.ts
Refs  reduct-storage/reduct-storage#131
Change
We're hashing the API token with the `sjcl` library.
Since Reduct Storage v0.7 it is not needed, and we can get rid of `sjcl`.
Nope
> Remove hash for api token

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- src/Bucket.ts
- src/Client.ts
- test/Bucket.test.ts
Closes #
Update
The SDK supports API v0.8
The SDK supports API v1.0
Yes. API v0.8 and API v1.0 aren't compatible. The `Bucket.list` method was removed
> Support Reduct Storage API v1.0

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- examples/HelloWorld.js
- src/Bucket.ts
- src/Record.ts
- test/Bucket.test.ts
- test/Client.test.ts
Closes #42
Refactoring
See #42 
```js
const bucket = await client.getOrCreateBucket("bucket");
const timestamp = Date.now() * 1000;
let record = await bucket.beginWrite("entry-1", timestamp);
await record.write("Hello, World!");
record = await bucket.beginRead("entry-1", timestamp);
console.log(await record.readAsString());
```
Yes
> Refactor read and write operations with records

- CHANGELOG.md
- README.md
- src/Client.ts
- test/Client.test.ts
- test/Token.test.ts
Closes #48 
Feature
See #48 
Ive added `Client.me` method to get the current API token with its permission. It is the only feature which was added in ReductStore v1.2.
No
> Add method Client.me to get current permissions

- CHANGELOG.md
- package.json
- src/APIError.ts
- test/Client.test.ts
Closes #
Update
ReductStorage sends an error message in the  `x-reduct-error ` message, but the SDK uses JSON body which is emptz for HEAD.
Use the header which works always.
No
> Use x-reduct-error header for error message

- CHANGELOG.md
- README.md
- src/Bucket.ts
- src/Record.ts
- src/index.ts
- test/Bucket.test.ts
Closes #
Feature
Since 1.3 version, ReductStore supports Content-Type header for records. However, we don"t provide it in the SDK
I added WriteOption type to pass labels, timestamps, and content type.
No
> Add support for content type

- CHANGELOG.md
- src/Client.ts
- test/Bucket.test.ts
Closes #
Bug fix
The SDK uses hooks for encoding and decoding big integers , unfortunately it is  an error-prone approach. 
A record which is sent as Buffer where serialized into JSON. 
I've added a check for the Buffer type, but  it is just a work around.
No
> Fix sending Buffer

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- package-lock.json
- src/Bucket.ts
Closes #
Feature
Since version 1.5, ReductStore supports an endpoint with bathed records. However, the SDK doesn't support this.
The `Bucket.query` method checks the API version and if it's v1.5 it uses the batched request.
No
> Support for `GET /api/v1/b/:bucket/:entry/batch` endpoint

- CHANGELOG.md
- src/Bucket.ts
- test/Bucket.test.ts
Closes #
Feature
Since v1.5, ReductStore provides HEAD method to read only meta information about records. The SDK doesn't support this.
I've implemented it as an option for the `Bucket.beginRead` and `Bucket.query` methods
No
> Add `head` option to read only meta information about records

- CHANGELOG.md
- src/Bucket.ts
- test/Bucket.test.ts
Closes #64
Feature
See #64 
I've added the `limit` option to query options.
No
> Add limit option to query

- .readthedocs.yml
- CHANGELOG.md
- mkdocs.yml
- src/Batch.ts
- src/Bucket.ts
- src/BucketInfo.ts
- src/Token.ts
- test/Bucket.test.ts
- test/Token.test.ts
Closes #67
Feature 
See #67 
I've added the `Batch` class and the `Bucket.startWriteBatch` method for batch writing:
```javascript
const bucket: Bucket = await client.getBucket("bucket");
const batch = await bucket.beginWriteBatch("entry-10");
batch.add(1000n, "somedata1");
batch.add(2000n, "somedata2", "text/plain");
batch.add(3000n, "somedata3", undefined, {label1: "value1", label2: "value2"});
await batch.write();
``` 
The PR also provides the `isProvisioned` flag for the `Token` and `BucketInfo` classes.
No
> Add support for ReductStore API v1.7 

- CHANGELOG.md
- src/BucketInfo.ts
- src/Token.ts
Closes #
Bugfix
The backward compatibility was broken in v1.7 because the `isProvisioned` field wasn't optional
The field is optional now
No
> make isProvisioned optional

- CHANGELOG.md
- src/Bucket.ts
- test/Bucket.test.ts
Closes #70 
Bug fix
See #70 
The problem was that the `Stream.Readable.read` was misused and worked only for small records. I've fixed the bug and added a test with querying records of 1 Mb. 
No
> RS-56: Fix queering batched records

- src/Bucket.ts
Closes #72 
Bug fix
See #72 
When a record was received from a batch body, the promise removes the error handler.
No
> Fix  `MaxListenersExceededWarning` warn in `Bucket.query` method

- CHANGELOG.md
- README.md
- docs/quick-start.md
- test/Bucket.test.ts
- test/Client.test.ts
With new website we need to change links from docs.reduct.store to reduct.store/docs
> Update documentation link to new website

- .gitignore
- CHANGELOG.md
- src/Client.ts
Closes #
Bug fix
The https.Agent class is part of Node.js's https module, which is not available in the browser. Browsers have their own way of handling HTTPS requests and do not expose a way to configure HTTP agents like Node.js does. 
No
No
> RS-224: Use https Agent only outside browser environment

- CHANGELOG.md
- README.md
- src/Bucket.ts
- src/Client.ts
- test/Bucket.test.ts
- test/Client.test.ts
- test/Helpers.ts
Closes #
Feature
I've added new `each_n` and `each_s` parameters to `QueryOptions` method.
reductstore/reductstore#465
No
> RS-261: Add `each_n` and `each_s` query parameters

- CHANGELOG.md
- src/messages/ReplicationSettings.ts
- test/Replication.test.ts
Closes #
Bug fix
The `each_n` and `each_s`  replication parameters don't follow the name convention. Renamed to `eachS` and `eachN`.
No
Yes, but it is not a critical part.
> RS-319: fix name convention for replication settings

- CHANGELOG.md
- src/Bucket.ts
- src/Record.ts
- test/Bucket.test.ts
- test/Client.test.ts
Closes #
Bug fix
- Detect if the module is running in the browser
- Request ArrayBuffer instead of Stream when running in the browser
- Only fetch single records in the browser (not batch)
- Convert ArrayBuffer to Node.js Buffer (the read() method always gives a Node.js Buffer)
No
No
Because the read function gives a Node.js Buffer object, applications running in the browser must install [stream-browserify](https://www.npmjs.com/package/stream-browserify).
> RS-394: Add query support for browser

- .github/workflows/ci.yml
- CHANGELOG.md
- src/Bucket.ts
Closes #
Bug fix
We use the stream response type for the HEAD requests, they hang in the event loop if a user doesn't call the Record.read() method. This is undetectable.
No
No
> Fix hanging HEAD requests

- CHANGELOG.md
- src/Batch.ts
- src/Bucket.ts
- test/Bucket.test.ts
Closes #
Feature
The following methods have been added:
* Bucket.removeRecord - to remove a single record 
* Bucket.beginRemoveBatch - to remove a batch of records 
* Bucket.removeQuery - to remove records within a time range with filtering by labels
reductstore/reductstore#560
Fixed a typo in the QueryOptions:  poolInterval -> pollInterval.
> RS-418: Implement remove record API

- CHANGELOG.md
- src/Bucket.ts
- test/Bucket.test.ts
Closes #
Feature
The `Bucket.renameEntry` method was added.
https://github.com/reductstore/reductstore/pull/596
No
> RS-388: Add Bucket.renameEntry method

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- src/Bucket.ts
- src/messages/QueryEntry.ts
- test/Bucket.test.ts
- test/Replication.test.ts
Closes #
Feature
The PR adds the ext parameter to the Bucket.query method to process data with extensions:
```js
for await (const record of bucket.query("entry-1", undefined, undefined, { ext_name: { param: {} } })) {
}
```
https://github.com/reductstore/reductstore/pull/762
No
> RS-628: Support ext parameter in query

- CHANGELOG.md
- src/Bucket.ts
- src/messages/QueryEntry.ts
- test/Bucket.test.ts
Closes #
Bug fix
When a user specifies a `when' condition, the SDK starts using the POST query endpoint, but ignores the start and stop parameters.  The PR fixes the issues and adds a test for this case.
https://github.com/reductstore/web-console/issues/94
No
> Fix start and stop parameters for POST query  request

- CHANGELOG.md
- src/Record.ts
- test/Bucket.test.ts
Closes #
Bug fix
The compatibility was broken #99 and the method Record.read() returned the `Uint8Array ` type instead of the `Buffer`. The PR returns the original type.
#99
No
> Return broken signature Record.read() -> Buffer

- CHANGELOG.md
- src/http/HttpClient.ts
- test/Client.test.ts
- test/utils/Helpers.ts
Closes #107 
Bug fix
Use `undici` dispatcher  with `rejectUnauthorized: false` to bypass SSL validation in Node.js when `verifySSL: false`
#107 
No
> 107: Bug replace agent with dispatcher in nodejs fetch implementation
