.github/workflows/ci.yml, README.md, jest.config.cjs, package-lock.json, package.json, src/Bucket.ts, src/Client.ts, test/Bucket.test.ts, test/Client.test.ts, test/Helpers.ts
=> [#3] Add token authentication

.readthedocs.yml, docs/requirements.txt, mkdocs.yml, package-lock.json, package.json, src/Client.ts
=> [#2]  Setup mkdocs

CHANGELOG.md, README.md, src/index.ts
=> [#7] Add quota type to index

README.md, src/APIError.ts, src/Client.ts, test/Client.test.ts
=> [#8] Add Client.getOrCreateBucket

CHANGELOG.md, src/Bucket.ts, test/Bucket.test.ts
=> [#15] Fix reading big records

CHANGELOG.md, src/Bucket.ts
=> [#14] Fix signature Bucket.list

CHANGELOG.md, examples/HelloWorld.js, src/Bucket.ts, test/Bucket.test.ts
=> [#11] Use Buffer read and write records

CHANGELOG.md, src/Client.ts, test/Client.test.ts
=> [#20] Add timeout to ClientOptions

CHANGELOG.md, package-lock.json, package.json, src/APIError.ts, src/Client.ts, src/EntryInfo.ts
The client failed to an infinite loop when it updated the token.
=> Fix updating refresh token

CHANGELOG.md, src/BucketSettings.ts, test/Bucket.test.ts, test/Client.test.ts
=> [#27] Support HTTP API v0.6.0 

CHANGELOG.md, src/Bucket.ts, test/Bucket.test.ts
=> [#28] Implement streaming data

.pre-commit-config.yaml, CHANGELOG.md, src/APIError.ts, test/Client.test.ts
=> [#25] Add original exception to APIError

CHANGELOG.md, src/BucketSettings.ts, test/Client.test.ts
**Closes** #34
Bug fix
`BucketSettings`  isn't serialized with  `maxBlockRecords` parameter.
I add `maxBlockRecords` to serialization
=> [#34] Fix BucketSetting serialisation

CHANGELOG.md, README.md, src/Client.ts, test/Client.test.ts
Closes #39 
Update
The SDK supports Reduct Storage HTTP API v0.7
Update for Reduct Storage HTTP API v0.8
No
=> Use api token for authentication

CHANGELOG.md, src/index.ts
Closes #
Bug fix
Token and TokenPermissions isn't in index.ts
They are there
No
=> Add token and permissions to index

.github/workflows/ci.yml, CHANGELOG.md, docs/quick-start.md, examples/QuickStart.js, mkdocs.yml
Closes #52 
Docs update
See #52 
Now, a user has an example with typical use cases.
No
=> QuickStart example and documentation

CHANGELOG.md, README.md, src/Bucket.ts, src/Record.ts, test/Bucket.test.ts
Closes #53 
Feature
See #53 
A user can read and write labels like a key-value map as well as use them as filters for querying data.
No
=> Add support labels

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, package-lock.json, package.json, src/APIError.ts, src/Bucket.ts, src/BucketSettings.ts, src/Client.ts, src/ServerInfo.ts, test/Bucket.test.ts, test/Client.test.ts
Closes #
Bug fix
Unfortunately, C++ Protobuf implementation sent integers as sting. It was changed in Rust implementation.
The library aligned with the new implementation.
Yes, we drop support of 1.3.0 version.
=> Fix JSON parsing for big integers

CHANGELOG.md, README.md, package-lock.json, package.json, src/Bucket.ts, test/Bucket.test.ts, test/Client.test.ts
Closes #64 
Feature
See #64 
I've added the `Bucket.remove_entry` method and tests
No
=> Implement removing entry

CHANGELOG.md, src/Client.ts, test/Bucket.test.ts
Closes #
Bugfix
Axious has a limit of 10 MiB on the size of the content.
I've disabled the limit so that users can write large blobs.
No
=> Fix content length limit

.github/workflows/ci.yml, CHANGELOG.md, examples/HelloWorld.js, examples/QuickStart.js, examples/Subscription.js, src/Client.ts, test/Bucket.test.ts, test/Client.test.ts
Closes #
Feature
I've added the `verifySSL` to  the client options to work with self-signed certificates.
--
No
=> RS-183: Add `verifySSL` option

.github/workflows/ci.yml, CHANGELOG.md, README.md, src/index.ts, src/messages/ServerInfo.ts, test/Client.test.ts, test/Helpers.ts
Closes #
Feature
Add license information to `ServerInfo` for the ReductStore HTTP 1.9
--
No
=> RS-178: Add license information to `ServerInfo`

.github/workflows/ci.yml, CHANGELOG.md
Closes #
(Bug fix, feature, docs update, ...)
(Describe the changes)
(Add links to related issues)
(What changes might users need to make in their application due to this PR?)
=> Update GitHub actions to get rid of warnings

CHANGELOG.md, src/index.ts
Closes #
Bug fix
I've added the Batch class into `export` in the index file.
No
No
=> Add Batch class in export

CHANGELOG.md, README.md, src/Client.ts, src/messages/BucketSettings.ts, src/messages/Diagnostics.ts, src/messages/ReplicationInfo.ts, src/messages/ReplicationSettings.ts, test/Replication.test.ts, test/Token.test.ts
Closes #
Feature
Add the replication settings implemented in  reductstore/reductstore#465
reductstore/reductstore#465
No
=> RS-311:  add each_s and each_n replication settings

CHANGELOG.md, src/Batch.ts, src/Bucket.ts, test/Bucket.test.ts
Closes #
Feature
Add `Bucket.update` and `Bucket.beginUpdateBatch` methods to change labels.
reductstore/reductstore#517
No
=> RS-31: Add changing labels

CHANGELOG.md, src/messages/BucketSettings.ts, test/Client.test.ts
Closes #
Feature
Support for the hard bucket quota from ReductStore API v1.12
reductstore/reductstore#570
No
=> RS-289: Support QuotaType.HARD

CHANGELOG.md, src/Bucket.ts, test/Bucket.test.ts, test/Client.test.ts
Closes #
Feature
The `Bucket.rename` method was added.
https://github.com/reductstore/reductstore/pull/597
No
=> RS-419: Add  Bucket.rename method

CHANGELOG.md, src/Batch.ts, test/Bucket.test.ts
Closes #
Feature
Additional methods for better experience with batching:
* `Batch.size()` - returns size of the batched data in bytes
* `Batch.recordCount()` - returns number of records in the batch
* `Batch.lastAccessTime()` - returns a timestamp when last record was added
* `Batch.clear()` - removes all records from the batch and reset the counts
No
No
=> RS-462: Improve batching

CHANGELOG.md, README.md, src/Bucket.ts, src/index.ts, src/messages/QueryEntry.ts, test/Bucket.test.ts
Closes #
Feature 
The PR applies the following changes:
* Add support for https://www.reduct.store/docs/next/http-api/entry-api/run_query
https://github.com/reductstore/reductstore/pull/635
https://github.com/reductstore/reductstore/pull/663
No
=> RS-543: Support conditional query

CHANGELOG.md, Dockerfile, README.md, examples/HelloWorld.js, package-lock.json, package.json, src/messages/ReplicationSettings.ts, test/Replication.test.ts
Closes #
Feature
The PR adds the `ReplicationSettings.when` field to pass the conditional query to the replication settings.
https://github.com/reductstore/reductstore/pull/687
No
=> RS-550: Add when condition to replication settings 
